(()=>{
'use strict';

const DIG_KEY='efd_digital_game_v20';
const DIG_VERSION=20;

const NAMES={1:'EL PERFECCIONISTA',2:'LA ENCANTADORA',3:'EL TRIUNFADOR',4:'LA ARTISTA',5:'EL INVESTIGADOR',6:'LA PREVENCIONISTA',7:'LA ILUSIONISTA',8:'EL PROTECTOR',9:'LA IMPERTURBABLE'};
const VIRTUES={1:'Disciplina',2:'Empatía',3:'Adaptabilidad',4:'Sensibilidad',5:'Conocimiento',6:'Previsión',7:'Ingenio',8:'Fuerza',9:'Armonía'};
const DEFECTS={1:'Ira',2:'Orgullo',3:'Vanidad',4:'Envidia',5:'Avaricia',6:'Cobardía',7:'Gula',8:'Lujuria',9:'Pereza'};
const WINGS={1:[9,2],2:[1,3],3:[2,4],4:[3,5],5:[4,6],6:[5,7],7:[6,8],8:[7,9],9:[8,1]};
const ARROWS={1:[4,7],2:[4,8],3:[6,9],4:[1,2],5:[7,8],6:[3,9],7:[1,5],8:[2,5],9:[3,6]};
const TEMPS={mental:{label:'🧠 MENTAL',cls:'mental',chars:[5,6,7]},emotional:{label:'❤️ EMOCIONAL',cls:'emotional',chars:[2,3,4]},visceral:{label:'👊 VISCERAL',cls:'visceral',chars:[8,9,1]}};
const CHAR_TEMP={1:'visceral',2:'emotional',3:'emotional',4:'emotional',5:'mental',6:'mental',7:'mental',8:'visceral',9:'visceral'};

// Tablero: círculo exterior = Alas. Líneas interiores = Flechas.
const ORDER=[9,1,2,3,4,5,6,7,8];
const RADIUS=42;
const POS={};
ORDER.forEach((n,i)=>{const a=(-90+i*40)*Math.PI/180;POS[n]=[50+RADIUS*Math.cos(a),50+RADIUS*Math.sin(a)]});
const OUTER=[[9,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9]];
const HEXAD=[[1,4],[4,2],[2,8],[8,5],[5,7],[7,1]];
const TRIANGLE=[[3,6],[6,9],[9,3]];
const INNER=[...HEXAD,...TRIANGLE];
const CYCLE=['instinct','things','choose'];
const OUTER_TYPES=OUTER.map((_,i)=>CYCLE[i%3]);
const INNER_TYPES=[...HEXAD.map((_,i)=>CYCLE[i%3]),...TRIANGLE.map((_,i)=>CYCLE[i%3])];

// Elige Tú con dirección clara. Sustituye también el bloque del modo físico.
const BETTER_CHOOSE=[
{id:'ELI20-01',texto:'ATAJO O LIMPIEZA\n\nElige UNA:\n✨ Gana una Virtud de tu mapa que te falte y recibe también el Defecto asociado a esa Virtud.\n☠️ O elimina uno de tus Defectos.'},
{id:'ELI20-02',texto:'TÚ DECIDES QUIÉN PAGA\n\nElige a otro jugador y haz UNA:\n🎯 Róbale una Virtud que tenga.\n☠️ O entrégale uno de tus Defectos.'},
{id:'ELI20-03',texto:'RECICLA LO QUE NO TE SIRVE\n\nElige UNA:\n🔄 Cambia una Virtud que NO forme parte de tu mapa por una Virtud de tu mapa que te falte.\n🧹 O descarta dos Virtudes cualesquiera para eliminar hasta dos Defectos.'},
{id:'ELI20-04',texto:'¿TE LA JUEGAS?\n\nElige UNA:\n🎲 Arriesga: tira el dado. 4–6 → gana una Virtud de tu mapa que te falte. 1–3 → recibe el Defecto asociado a esa Virtud.\n🛡️ O juega seguro: elimina un Defecto.'},
{id:'ELI20-05',texto:'NEGOCIACIÓN POCO ELEGANTE\n\nElige a otro jugador y haz UNA:\n✨ Intercambiad una Virtud cada uno.\n☠️ O intercambiad un Defecto cada uno.'},
{id:'ELI20-06',texto:'CAMBIO DE PRIORIDADES\n\nElige UNA:\n⭐ Descarta una Virtud ajena a tu mapa y roba otra al azar a un rival.\n🧽 O elimina un Defecto y descarta también una Virtud cualquiera.'},
{id:'ELI20-07',texto:'AHORA MANDO YO\n\nElige UNA:\n🚶 En tu próximo turno, después de tirar, puedes sumar o restar 1 al resultado.\n🎯 O elige directamente qué tipo de casilla quieres resolver la próxima vez que caigas en una acción.'},
{id:'ELI20-08',texto:'PROTEGE LO IMPORTANTE\n\nElige UNA:\n🛡️ Una de tus Virtudes no puede ser robada hasta tu próximo turno.\n☠️ O elimina el Defecto del mismo número que una Virtud que ya tengas.'},
{id:'ELI20-09',texto:'DOBLE O NADA\n\nElige UNA:\n🔥 Tu próxima pregunta vale doble: si aciertas ganas 2 Virtudes; si fallas recibes 2 Defectos.\n😇 O no arriesgues y elimina un Defecto ahora.'},
{id:'ELI20-10',texto:'TRUEQUE CON EL UNIVERSO\n\nElige UNA:\n✨ Entrega una Virtud a otro jugador y elimina dos Defectos tuyos.\n🎁 O entrega un Defecto a otro jugador y roba una Virtud suya.'},
{id:'ELI20-11',texto:'CAMBIO DE RUMBO\n\nElige UNA:\n🧭 Muévete inmediatamente a una casilla conectada con la tuya y resuélvela.\n🧘 O quédate donde estás y elimina un Defecto.'},
{id:'ELI20-12',texto:'PRIORIDAD ABSOLUTA\n\nMira tu mapa de 5 Virtudes y elige UNA:\n✨ La próxima Virtud que ganes debe ser una concreta de tu mapa que te falte.\n☠️ O cancela esta carta y elimina cualquier Defecto.'}
];
try{if(typeof DATA!=='undefined'&&Array.isArray(DATA.elige_tu)){DATA.elige_tu.splice(0,DATA.elige_tu.length,...BETTER_CHOOSE)}}catch(e){}

let modeScreen,setupScreen,digitalScreen,digOverlay,dig=null;

function injectCSS(){const s=document.createElement('style');s.id='digitalBoardV20Styles';s.textContent=`
.choose-text{white-space:pre-line}.mode-hero,.dig-hero{position:relative;overflow:hidden;border:1px solid rgba(35,231,255,.28);border-radius:22px;background:radial-gradient(circle at 0% 0%,rgba(35,231,255,.12),transparent 38%),radial-gradient(circle at 100% 100%,rgba(140,82,255,.13),transparent 42%),#0a0a12;padding:20px 18px;margin-bottom:14px}.mode-hero:before,.dig-hero:before{content:"";position:absolute;left:0;right:0;top:0;height:2px;background:linear-gradient(90deg,var(--cyan),var(--violet),var(--magenta))}.mode-kicker,.dig-kicker{margin:0 0 7px;color:var(--cyan);font-size:.65rem;font-weight:950;letter-spacing:.17em}.mode-title,.dig-title{margin:0 0 8px;font-size:clamp(1.55rem,7vw,2.15rem);line-height:1;font-weight:950}.mode-sub,.dig-sub{margin:0;color:#c5c7d1;line-height:1.45;font-size:.9rem}.mode-stack{display:grid;gap:11px}.mode-choice{width:100%;min-height:86px;border-radius:19px;background:#0a0a11;color:#fff;text-align:left;padding:15px 16px;border:1px solid rgba(255,255,255,.12);cursor:pointer}.mode-choice strong{display:block;font-size:1.04rem}.mode-choice small{display:block;margin-top:5px;color:#aeb1be;font-size:.72rem;line-height:1.35}.mode-choice.physical{border-color:rgba(255,216,61,.42)}.mode-choice.digital{border-color:rgba(35,231,255,.55)}
.dig-setup-box{border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.025);border-radius:18px;padding:15px;margin-bottom:11px}.dig-setup-box h3{margin:0 0 10px;font-size:.92rem}.dig-select,.dig-name-input{width:100%;height:48px;border-radius:13px;border:1px solid rgba(255,255,255,.15);background:#08080e;color:#fff;padding:0 12px;font:inherit}.dig-name-grid{display:grid;gap:8px;margin-top:10px}.dig-start{width:100%;min-height:57px;margin-top:4px}
.dig-topline{display:flex;align-items:stretch;justify-content:space-between;gap:9px;margin-bottom:10px}.dig-turn{flex:1;border:1px solid rgba(255,255,255,.10);border-radius:17px;background:rgba(255,255,255,.025);padding:12px}.dig-turn .tiny{font-size:.61rem;color:#858999;font-weight:900;letter-spacing:.12em}.dig-turn h2{margin:4px 0 5px;font-size:1.15rem}.dig-resource-mini{margin-top:7px;color:#b7bbc7;font-size:.69rem;font-weight:850}.dig-temp{display:inline-flex;padding:5px 8px;border-radius:999px;font-size:.63rem;font-weight:950;border:1px solid rgba(255,255,255,.12)}.dig-temp.mental{color:#92c4ff;background:rgba(47,140,255,.08)}.dig-temp.emotional{color:#ff9ab0;background:rgba(255,64,95,.08)}.dig-temp.visceral{color:#ffe68b;background:rgba(255,216,61,.08)}.dig-progress{min-width:74px;border:1px solid rgba(109,255,186,.22);border-radius:17px;background:rgba(109,255,186,.045);padding:12px 9px;text-align:center}.dig-progress strong{display:block;font-size:1.35rem;color:var(--green)}.dig-progress small{font-size:.56rem;color:#aab0b8;font-weight:900;letter-spacing:.08em}
.dig-board-shell{position:relative;width:100%;aspect-ratio:1;border-radius:24px;border:1px solid rgba(35,231,255,.18);background:radial-gradient(circle at 50% 50%,rgba(140,82,255,.09),transparent 43%),rgba(5,5,9,.87);overflow:hidden;box-shadow:inset 0 0 45px rgba(35,231,255,.03)}.dig-lines{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.dig-lines circle{fill:none;stroke:rgba(35,231,255,.25);stroke-width:1.3}.dig-lines line.hexad{stroke:rgba(255,43,214,.28);stroke-width:1.35}.dig-lines line.triangle{stroke:rgba(140,82,255,.38);stroke-width:1.5}.dig-center-note{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);text-align:center;pointer-events:none;color:#6f7380;font-size:.49rem;font-weight:950;letter-spacing:.08em;line-height:1.5;z-index:1}.dig-center-note strong{color:#a8acb8;font-size:.55rem}.dig-node{position:absolute;transform:translate(-50%,-50%);display:grid;place-items:center;border-radius:999px;z-index:2;transition:.18s ease}.dig-node.char{width:45px;height:45px;background:#0b0d15;color:#fff;font-size:1.04rem;font-weight:950}.dig-node.char.mental{border:1px solid rgba(47,140,255,.72)}.dig-node.char.emotional{border:1px solid rgba(255,64,95,.72)}.dig-node.char.visceral{border:1px solid rgba(255,216,61,.72)}.dig-node.action{width:31px;height:31px;border:1px solid rgba(255,255,255,.14);background:#0c0c13;font-size:.86rem}.dig-node.action.instinct{border-color:rgba(47,140,255,.62)}.dig-node.action.things{border-color:rgba(255,216,61,.62)}.dig-node.action.choose{border-color:rgba(255,64,95,.62)}.dig-node.reachable{cursor:pointer;transform:translate(-50%,-50%) scale(1.14);box-shadow:0 0 0 3px rgba(109,255,186,.14),0 0 25px rgba(109,255,186,.35);border-color:rgba(109,255,186,.95)}.dig-node.current{box-shadow:0 0 0 3px rgba(255,255,255,.09),0 0 24px rgba(255,255,255,.18)}.dig-tokens{position:absolute;left:50%;top:100%;transform:translate(-50%,3px);display:flex;gap:2px;white-space:nowrap}.dig-token{min-width:16px;height:16px;padding:0 4px;border-radius:999px;display:grid;place-items:center;font-size:.47rem;font-weight:950;color:#050509;background:#fff;border:1px solid rgba(0,0,0,.2)}.dig-board-legend{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.dig-board-legend span{padding:7px 4px;border-radius:10px;border:1px solid rgba(255,255,255,.08);text-align:center;font-size:.59rem;color:#aeb2bf}.dig-path-note{text-align:center;color:#737786;font-size:.58rem;margin-top:6px}
.dig-controls{display:grid;grid-template-columns:1.25fr .75fr;gap:9px;margin-top:10px}.dig-roll{min-height:56px;border-radius:16px;border:1px solid rgba(35,231,255,.55);background:linear-gradient(90deg,rgba(35,231,255,.12),rgba(140,82,255,.12)),#0a0a11;color:#fff;font-weight:950;cursor:pointer}.dig-roll:disabled{opacity:.48}.dig-die{min-height:56px;border-radius:16px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.035);display:grid;place-items:center;font-size:1.35rem;font-weight:950}.dig-msg{margin:9px 2px 0;color:#b9bdca;font-size:.78rem;line-height:1.4;min-height:22px}.dig-tools{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.dig-tool{min-height:46px;border-radius:13px;border:1px solid rgba(255,255,255,.11);background:rgba(255,255,255,.025);color:#eef0f6;font-size:.69rem;font-weight:900;padding:7px}.dig-order{margin-top:11px;border-top:1px solid rgba(255,255,255,.08);padding-top:10px;display:flex;gap:6px;overflow:auto}.dig-order-chip{flex:0 0 auto;padding:6px 8px;border-radius:999px;border:1px solid rgba(255,255,255,.10);font-size:.61rem;color:#aeb1bc}.dig-order-chip.active{color:#fff;border-color:rgba(109,255,186,.45);background:rgba(109,255,186,.06)}
.dig-overlay{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.78);backdrop-filter:blur(8px);display:none;align-items:flex-end;justify-content:center;padding:12px}.dig-overlay.show{display:flex}.dig-modal{width:min(100%,680px);max-height:90dvh;overflow:auto;border:1px solid rgba(255,255,255,.14);border-radius:24px;background:#090910;padding:18px}.dig-modal-kicker{margin:0 0 6px;color:var(--cyan);font-size:.62rem;font-weight:950;letter-spacing:.15em}.dig-modal h2{margin:0 0 10px;font-size:1.35rem;line-height:1.1}.dig-modal p{line-height:1.48}.dig-private{border:1px solid rgba(255,216,61,.22);background:rgba(255,216,61,.045);border-radius:13px;padding:10px 11px;color:#fff2b5;font-size:.78rem;margin-bottom:12px}.dig-goal-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin:11px 0}.dig-goal{padding:8px 4px;border-radius:11px;border:1px solid rgba(255,255,255,.10);text-align:center;font-size:.58rem;color:#9195a3}.dig-goal.done{color:#dffff0;border-color:rgba(109,255,186,.38);background:rgba(109,255,186,.06)}.dig-goal strong{display:block;font-size:.7rem;color:#fff;margin-bottom:3px}.dig-modal-actions{display:grid;gap:8px;margin-top:13px}.dig-modal-actions.two{grid-template-columns:1fr 1fr}.dig-action-btn{min-height:48px;border-radius:13px;border:1px solid rgba(35,231,255,.30);background:rgba(35,231,255,.055);color:#fff;font-weight:950;cursor:pointer;padding:10px}.dig-action-btn.ghost{border-color:rgba(255,255,255,.11);background:rgba(255,255,255,.025);color:#b8bbc6}.dig-action-btn.good{border-color:rgba(109,255,186,.38);background:rgba(109,255,186,.065);color:#dffff0}.dig-action-btn.bad{border-color:rgba(255,64,95,.35);background:rgba(255,64,95,.06);color:#ffd6de}
.dig-question{font-size:1.03rem;font-weight:850;line-height:1.43;margin:8px 0 12px}.dig-option{width:100%;display:flex;gap:10px;text-align:left;padding:11px;border:1px solid rgba(255,255,255,.10);border-radius:12px;margin-bottom:7px;line-height:1.4;font-size:.87rem;background:rgba(255,255,255,.02);color:#fff;cursor:pointer}.dig-option:disabled{cursor:default;opacity:.72}.dig-option.correct{opacity:1;border-color:rgba(109,255,186,.62);background:rgba(109,255,186,.08)}.dig-option.wrong{opacity:1;border-color:rgba(255,64,95,.58);background:rgba(255,64,95,.075)}.dig-letter{flex:0 0 27px;height:27px;border-radius:8px;display:grid;place-items:center;background:rgba(255,255,255,.06);font-weight:950}.dig-answer{margin-top:10px;padding:11px;border-radius:11px;font-weight:900;line-height:1.4}.dig-answer.good{background:rgba(109,255,186,.07);border:1px solid rgba(109,255,186,.25);color:#dffff0}.dig-answer.bad{background:rgba(255,64,95,.06);border:1px solid rgba(255,64,95,.24);color:#ffd6de}.dig-resource-row{display:grid;grid-template-columns:1fr auto 1fr;gap:7px;align-items:stretch;margin-bottom:7px}.dig-resource{border:1px solid rgba(255,255,255,.10);border-radius:12px;padding:9px}.dig-resource.target{border-color:rgba(109,255,186,.24);background:rgba(109,255,186,.035)}.dig-resource strong{display:block;font-size:.76rem}.dig-resource small{display:block;color:#868a98;font-size:.58rem;margin-top:2px}.dig-counter{display:flex;align-items:center;gap:5px;margin-top:7px}.dig-counter button{width:30px;height:30px;border-radius:8px;border:1px solid rgba(255,255,255,.12);background:#11111a;color:#fff;font-weight:950}.dig-counter span{min-width:18px;text-align:center;font-weight:950}.dig-vs{display:grid;place-items:center;color:#656977;font-size:.56rem;font-weight:950}.dig-effect-card{border:1px solid rgba(255,255,255,.11);border-radius:16px;background:rgba(255,255,255,.025);padding:14px;margin:10px 0}.dig-effect-card h3{margin:0 0 7px}.dig-effect-card .fl{color:#989ca9;font-style:italic;font-size:.82rem}.dig-effect-card .ef{white-space:pre-line;color:#eef0f6;font-size:.88rem;line-height:1.48}.dig-win{text-align:center}.dig-win .crown{font-size:3rem}`;document.head.appendChild(s)}

function buildScreens(){const home=document.getElementById('home');modeScreen=document.createElement('main');modeScreen.id='gameMode';modeScreen.className='screen';modeScreen.innerHTML=`<section class="mode-hero"><p class="mode-kicker">EL FAVORITO DE DIOS</p><h2 class="mode-title">¿Cómo quieres jugar?</h2><p class="mode-sub">El juego físico sigue intacto. El modo digital ya incluye tablero, dado, fichas, preguntas y recursos.</p></section><div class="mode-stack"><button class="mode-choice physical" id="modePhysical"><strong>🎲 JUGAR CON TABLERO FÍSICO</strong><small>Usa la miniweb como asistente.</small></button><button class="mode-choice digital" id="modeDigital"><strong>🕹️ JUGAR TODO EN LA APP</strong><small>Tablero digital completo · pass & play.</small></button></div><button class="btn btn-ghost" id="modeBack" style="margin-top:12px">← VOLVER</button>`;home.parentNode.insertBefore(modeScreen,home);setupScreen=document.createElement('main');setupScreen.id='digitalSetup';setupScreen.className='screen';setupScreen.innerHTML=`<section class="dig-hero"><p class="dig-kicker">MODO DIGITAL · PASS & PLAY</p><h2 class="dig-title">Preparar partida</h2><p class="dig-sub">El círculo exterior representa las Alas y las líneas interiores las Flechas. Los retos físicos de Instinto no aparecen en este modo.</p></section><div class="dig-setup-box"><h3>👥 ¿Cuántos jugadores?</h3><select class="dig-select" id="digPlayerCount"><option value="1">1 jugador</option><option value="2" selected>2 jugadores</option><option value="3">3 jugadores</option><option value="4">4 jugadores</option></select><div class="dig-name-grid" id="digNames"></div></div><button class="btn btn-primary dig-start" id="digCreate">🎲 CREAR PARTIDA</button><button class="btn btn-ghost" id="digSetupBack" style="margin-top:8px">← VOLVER</button>`;home.parentNode.insertBefore(setupScreen,home);digitalScreen=document.createElement('main');digitalScreen.id='digitalGame';digitalScreen.className='screen';home.parentNode.insertBefore(digitalScreen,home);digOverlay=document.createElement('div');digOverlay.id='digOverlay';digOverlay.className='dig-overlay';digOverlay.innerHTML='<div class="dig-modal" id="digModal"></div>';document.body.appendChild(digOverlay)}
function allScreens(){return [document.getElementById('introScreen'),modeScreen,setupScreen,digitalScreen,document.getElementById('home'),document.getElementById('game')].filter(Boolean)}
function activate(screen){allScreens().forEach(s=>s.classList.remove('active'));screen.classList.add('active');document.body.classList.remove('intro-mode');const r=document.getElementById('resetTop');if(r)r.style.display=(screen===document.getElementById('home')||screen===document.getElementById('game'))?'':'none';scrollTo(0,0)}
function showModes(){activate(modeScreen);document.getElementById('digResume')?.remove();if(loadDig()){const b=document.createElement('button');b.id='digResume';b.className='mode-choice digital';b.innerHTML='<strong>▶ CONTINUAR PARTIDA DIGITAL</strong><small>Retoma exactamente donde la dejaste.</small>';document.querySelector('.mode-stack').appendChild(b);b.onclick=()=>{dig=loadDig();renderDigitalGame()}}}
function showSetup(){activate(setupScreen);renderNameInputs()}
function renderNameInputs(){const count=Number(document.getElementById('digPlayerCount').value||2),box=document.getElementById('digNames'),old=[...box.querySelectorAll('input')].map(x=>x.value);box.innerHTML='';for(let i=0;i<count;i++){const x=document.createElement('input');x.className='dig-name-input';x.maxLength=22;x.placeholder=`Jugador ${i+1}`;x.value=old[i]||'';box.appendChild(x)}}
function d6(){return 1+Math.floor(Math.random()*6)}function roll3(){return [d6(),d6(),d6()]}function uniqueOrderRoll(players){let pending=players.slice();while(true){pending.forEach(p=>{p.orderDice=roll3();p.orderSum=p.orderDice.reduce((a,b)=>a+b,0)});const groups={};pending.forEach(p=>(groups[p.orderSum]??=[]).push(p));const ties=Object.values(groups).filter(g=>g.length>1).flat();if(!ties.length)break;pending=ties}}function temperamentRoll(){let vals={mental:d6(),emotional:d6(),visceral:d6()};while(true){const mx=Math.max(...Object.values(vals)),tied=Object.keys(vals).filter(k=>vals[k]===mx);if(tied.length===1)return {key:tied[0],rolls:vals};tied.forEach(k=>vals[k]=d6())}}function randomFrom(a){return a[Math.floor(Math.random()*a.length)]}function blankCounts(){const x={};for(let n=1;n<=9;n++)x[n]=0;return x}
function createDigitalGame(){const inputs=[...document.querySelectorAll('#digNames input')],players=inputs.map((input,i)=>({id:`p${Date.now()}_${i}`,name:input.value.trim()||`Jugador ${i+1}`,virtues:blankCounts(),defects:blankCounts(),effects:[]}));uniqueOrderRoll(players);players.sort((a,b)=>b.orderSum-a.orderSum);players.forEach(p=>{const tr=temperamentRoll();p.temperament=tr.key;p.tempRolls=tr.rolls;p.character=randomFrom(TEMPS[tr.key].chars);p.pos=`c${p.character}`;p.virtues[p.character]=1;p.defects[p.character]=1});dig={version:DIG_VERSION,players,turnIndex:0,die:null,reachable:[],message:'Pulsa TIRAR DADO para empezar.',winner:null,createdAt:Date.now()};saveDig();showSetupSummary()}
function showSetupSummary(){openOverlay(`<p class="dig-modal-kicker">ORDEN DE JUEGO</p><h2>🎲 Todo listo</h2><div class="dig-private">Las identidades son secretas. Cada jugador consulta la suya en su turno.</div>${dig.players.map((p,i)=>`<div class="dig-effect-card"><strong>${i+1}. ${escD(p.name)}</strong><br><span class="dig-temp ${TEMPS[p.temperament].cls}">${TEMPS[p.temperament].label}</span><p style="margin:7px 0 0;color:#a8abb8;font-size:.76rem">Orden: ${p.orderDice.join(' + ')} = <strong>${p.orderSum}</strong></p></div>`).join('')}<div class="dig-modal-actions"><button class="dig-action-btn good" id="digBegin">▶ EMPEZAR</button></div>`);document.getElementById('digBegin').onclick=()=>{closeOverlay();renderDigitalGame()}}
function saveDig(){localStorage.setItem(DIG_KEY,JSON.stringify(dig))}function loadDig(){try{const x=JSON.parse(localStorage.getItem(DIG_KEY)||'null');return x&&x.version===DIG_VERSION?x:null}catch(e){return null}}function escD(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function currentPlayer(){return dig.players[dig.turnIndex]}function totalCounts(obj){return Object.values(obj||{}).reduce((a,b)=>a+(Number(b)||0),0)}function targetNums(char){return [...new Set([char,...WINGS[char],...ARROWS[char]])]}function progressOf(p){return targetNums(p.character).filter(n=>(p.virtues[n]||0)>0).length}function checkWin(p){return targetNums(p.character).every(n=>(p.virtues[n]||0)>0)}
function outerPoint(a,b){const ia=ORDER.indexOf(a),ib=ORDER.indexOf(b);let a1=-90+ia*40,a2=-90+ib*40;if(Math.abs(a2-a1)>180){if(a1<a2)a1+=360;else a2+=360}const mid=(a1+a2)/2*Math.PI/180;return [50+RADIUS*Math.cos(mid),50+RADIUS*Math.sin(mid)]}function innerPoint(a,b,idx){const [ax,ay]=POS[a],[bx,by]=POS[b],t=.5;let x=ax+(bx-ax)*t,y=ay+(by-ay)*t,dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy)||1,offset=(idx%2===0?1:-1)*1.25;x+=(-dy/len)*offset;y+=(dx/len)*offset;return [x,y]}
function buildGraph(){const nodes={},adj={};Object.entries(POS).forEach(([n,[x,y]])=>nodes[`c${n}`]={id:`c${n}`,kind:'char',n:Number(n),x,y});const add=(a,b,type,id,x,y,route)=>{nodes[id]={id,kind:'action',action:type,x,y,route};for(const k of [`c${a}`,id,`c${b}`])adj[k]??=[];adj[`c${a}`].push(id);adj[id].push(`c${a}`,`c${b}`);adj[`c${b}`].push(id)};OUTER.forEach((e,i)=>{const [x,y]=outerPoint(...e);add(e[0],e[1],OUTER_TYPES[i],`o${e[0]}_${e[1]}`,x,y,'outer')});INNER.forEach((e,i)=>{const [x,y]=innerPoint(e[0],e[1],i);add(e[0],e[1],INNER_TYPES[i],`i${e[0]}_${e[1]}`,x,y,i<6?'hexad':'triangle')});return {nodes,adj}}const GRAPH=buildGraph();
function reachable(start,steps){const ends=new Set();function dfs(node,left,seen){if(left===0){ends.add(node);return}for(const nx of GRAPH.adj[node]||[]){if(seen.has(nx))continue;const ns=new Set(seen);ns.add(nx);dfs(nx,left-1,ns)}}dfs(start,steps,new Set([start]));return [...ends]}function iconForAction(k){return k==='instinct'?'🔵':k==='things'?'🟡':'🔴'}function labelForAction(k){return k==='instinct'?'INSTINTO':k==='things'?'COSAS QUE PASAN':'ELIGE TÚ'}
function renderBoardSVG(){const lines=[];HEXAD.forEach(([a,b])=>{const [x1,y1]=POS[a],[x2,y2]=POS[b];lines.push(`<line class="hexad" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"></line>`)});TRIANGLE.forEach(([a,b])=>{const [x1,y1]=POS[a],[x2,y2]=POS[b];lines.push(`<line class="triangle" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"></line>`)});return `<svg class="dig-lines" viewBox="0 0 100 100" preserveAspectRatio="none"><circle cx="50" cy="50" r="42"></circle>${lines.join('')}</svg>`}
function nodeHTML(node){const p=currentPlayer(),tokens=dig.players.filter(pl=>pl.pos===node.id).map(pl=>`<span class="dig-token">${escD(pl.name.slice(0,2).toUpperCase())}</span>`).join(''),reach=(dig.reachable||[]).includes(node.id),cur=p.pos===node.id,cls=`dig-node ${node.kind}${node.kind==='char'?' '+CHAR_TEMP[node.n]:' '+node.action}${reach?' reachable':''}${cur?' current':''}`,title=node.kind==='char'?`${NAMES[node.n]} · ${VIRTUES[node.n]}`:labelForAction(node.action),body=node.kind==='char'?node.n:iconForAction(node.action);return `<button class="${cls}" data-dnode="${node.id}" style="left:${node.x}%;top:${node.y}%" title="${escD(title)}">${body}<span class="dig-tokens">${tokens}</span></button>`}
function renderDigitalGame(){if(!dig)dig=loadDig();if(!dig)return showSetup();activate(digitalScreen);const p=currentPlayer(),progress=progressOf(p);digitalScreen.innerHTML=`<div class="dig-topline"><div class="dig-turn"><div class="tiny">TURNO ${dig.turnIndex+1} DE ${dig.players.length}</div><h2>${escD(p.name)}</h2><span class="dig-temp ${TEMPS[p.temperament].cls}">${TEMPS[p.temperament].label}</span><div class="dig-resource-mini">✨ ${totalCounts(p.virtues)} Virtudes · ☠️ ${totalCounts(p.defects)} Defectos</div></div><div class="dig-progress"><strong>${progress}/5</strong><small>MAPA</small></div></div><div class="dig-board-shell" id="digBoard">${renderBoardSVG()}<div class="dig-center-note"><strong>ALAS</strong> = CÍRCULO<br><strong>FLECHAS</strong> = INTERIOR</div>${Object.values(GRAPH.nodes).map(nodeHTML).join('')}</div><div class="dig-board-legend"><span>🔵 INSTINTO</span><span>🟡 COSAS</span><span>🔴 ELIGE TÚ</span></div><div class="dig-path-note">Los tres tipos se repiten con el mismo orden en el círculo, el hexágono y el triángulo.</div><div class="dig-controls"><button class="dig-roll" id="digRoll" ${dig.reachable?.length?'disabled':''}>🎲 ${dig.reachable?.length?'ELIGE DESTINO':'TIRAR DADO'}</button><div class="dig-die">${dig.die??'—'}</div></div><p class="dig-msg">${escD(dig.message||'')}</p><div class="dig-tools"><button class="dig-tool" id="digIdentity">👁 MI PERSONAJE</button><button class="dig-tool" id="digResources">🎒 MIS RECURSOS</button><button class="dig-tool" id="digEffects">⚡ EFECTOS</button></div><div class="dig-order">${dig.players.map((pl,i)=>`<span class="dig-order-chip ${i===dig.turnIndex?'active':''}">${i+1}. ${escD(pl.name)} · ${TEMPS[pl.temperament].label}</span>`).join('')}</div><button class="btn btn-ghost" id="digExit" style="margin-top:12px">← MENÚ DE JUEGO</button>`;document.getElementById('digRoll').onclick=rollDigital;document.getElementById('digIdentity').onclick=showPrivateIdentity;document.getElementById('digResources').onclick=()=>showResources(null);document.getElementById('digEffects').onclick=showEffects;document.getElementById('digExit').onclick=showModes;document.querySelectorAll('[data-dnode].reachable').forEach(b=>b.onclick=()=>moveTo(b.dataset.dnode));if(dig.winner)showWin(dig.players.find(x=>x.id===dig.winner))}
function rollDigital(){const d=d6(),p=currentPlayer();dig.die=d;dig.reachable=reachable(p.pos,d);dig.message=`Has sacado ${d}. Elige uno de los destinos iluminados.`;saveDig();renderDigitalGame()}function moveTo(nodeId){if(!(dig.reachable||[]).includes(nodeId))return;const p=currentPlayer();p.pos=nodeId;dig.reachable=[];dig.message='';saveDig();renderDigitalGame();setTimeout(()=>resolveLanding(nodeId),120)}function resolveLanding(nodeId){const node=GRAPH.nodes[nodeId];if(!node)return finishTurn();if(node.kind==='char')showLandingChoice(node.n);else showDigitalAction(node.action)}function openOverlay(html){document.getElementById('digModal').innerHTML=html;digOverlay.classList.add('show')}function closeOverlay(){digOverlay.classList.remove('show')}function finishTurn(){const winner=dig.players.find(checkWin);if(winner){dig.winner=winner.id;saveDig();closeOverlay();renderDigitalGame();return}dig.turnIndex=(dig.turnIndex+1)%dig.players.length;dig.die=null;dig.reachable=[];dig.message='Pulsa TIRAR DADO.';saveDig();closeOverlay();renderDigitalGame()}
function showWin(p){if(!p)return;openOverlay(`<div class="dig-win"><div class="crown">👑</div><p class="dig-modal-kicker">5 / 5 COMPLETADO</p><h2>${escD(p.name)} es EL FAVORITO DE DIOS</h2><p>Ha reunido la Virtud de su Personaje, sus dos Alas y sus dos Flechas.</p><div class="dig-modal-actions"><button class="dig-action-btn good" id="digWinClose">VER TABLERO</button><button class="dig-action-btn ghost" id="digNewGame">NUEVA PARTIDA DIGITAL</button></div></div>`);document.getElementById('digWinClose').onclick=()=>digOverlay.classList.remove('show');document.getElementById('digNewGame').onclick=()=>{localStorage.removeItem(DIG_KEY);dig=null;closeOverlay();showSetup()}}
function showPrivateIdentity(){const p=currentPlayer(),targets=targetNums(p.character);openOverlay(`<p class="dig-modal-kicker">SOLO ${escD(p.name).toUpperCase()}</p><h2>🔐 Tu Personaje</h2><div class="dig-private">Que nadie mire. Si alguien mira, se ha saltado la deducción por el método científico del morro.</div><div class="dig-effect-card"><h3>${NAMES[p.character]}</h3><span class="dig-temp ${TEMPS[p.temperament].cls}">${TEMPS[p.temperament].label}</span><p><strong>✨ Virtud propia:</strong> ${VIRTUES[p.character]}</p><p><strong>☠️ Defecto:</strong> ${DEFECTS[p.character]}</p><p><strong>🪽 Alas:</strong> ${WINGS[p.character].map(n=>VIRTUES[n]).join(' · ')}</p><p><strong>⚡ Flechas:</strong> ${ARROWS[p.character].map(n=>VIRTUES[n]).join(' · ')}</p></div><div class="dig-goal-grid">${targets.map(n=>`<div class="dig-goal ${(p.virtues[n]||0)>0?'done':''}"><strong>${escD(VIRTUES[n])}</strong>${n===p.character?'PROPIA':WINGS[p.character].includes(n)?'ALA':'FLECHA'}</div>`).join('')}</div><div class="dig-modal-actions"><button class="dig-action-btn good" id="digHideIdentity">🙈 OCULTAR</button></div>`);document.getElementById('digHideIdentity').onclick=closeOverlay}
function showLandingChoice(n){openOverlay(`<p class="dig-modal-kicker">HAS CAÍDO EN ${n}</p><h2>${NAMES[n]}</h2><p>Elige cómo quieres jugar esta casilla.</p><div class="dig-modal-actions"><button class="dig-action-btn" id="digSpecificQ">🎯 PREGUNTA DE ${NAMES[n]}</button><button class="dig-action-btn" id="digIdentityQ">🔎 ¿QUIÉN ES?</button></div>`);document.getElementById('digSpecificQ').onclick=()=>showDigitalQuestion(n);document.getElementById('digIdentityQ').onclick=()=>showDigitalQuestion('identity')}
function digPick(pool,key){let a=remaining(pool,key);if(!a.length){const s=state();delete s[key];save(s);a=remaining(pool,key)}if(!a.length)return null;const q=randomFrom(a);mark(key,q.id);return q}
function showDigitalQuestion(type){const pool=qPool(type==='identity'?IDENTITY:type),q=digPick(pool,`dig20_q_${type}`);if(!q){openOverlay('<h2>Sin preguntas disponibles</h2><div class="dig-modal-actions"><button class="dig-action-btn" id="digNoQ">CONTINUAR</button></div>');document.getElementById('digNoQ').onclick=finishTurn;return}const chip=type==='identity'?'🔎 ¿QUIÉN ES?':NAMES[type];openOverlay(`<p class="dig-modal-kicker">${chip}</p><h2 class="dig-question">${escD(q.pregunta)}</h2><div id="digOptionBox">${['A','B','C'].map(l=>`<button class="dig-option" data-digopt="${l}"><span class="dig-letter">${l}</span><span>${escD(q.opciones[l])}</span></button>`).join('')}</div><div id="digQuestionResult"></div>`);let answered=false;document.querySelectorAll('[data-digopt]').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;resolveDigitalAnswer(type,q,b.dataset.digopt)})}
function resolveDigitalAnswer(type,q,selected){const p=currentPlayer(),ok=selected===q.correcta;document.querySelectorAll('[data-digopt]').forEach(b=>{b.disabled=true;if(b.dataset.digopt===q.correcta)b.classList.add('correct');if(b.dataset.digopt===selected&&!ok)b.classList.add('wrong')});let msg='';if(type==='identity'){if(ok){const n=q.eneatipo;p.virtues[n]=(p.virtues[n]||0)+1;msg=`✅ CORRECTA · +1 ${VIRTUES[n]}. Ahora tienes ${p.virtues[n]}.`}else msg='❌ FALLIDA · En ¿QUIÉN ES? no recibes Defecto.'}else{const n=Number(type);if(ok){p.virtues[n]=(p.virtues[n]||0)+1;msg=`✅ CORRECTA · +1 ${VIRTUES[n]}. Ahora tienes ${p.virtues[n]}.`}else{p.defects[n]=(p.defects[n]||0)+1;msg=`❌ FALLIDA · +1 ${DEFECTS[n]}. Ahora tienes ${p.defects[n]}.`}}saveDig();document.getElementById('digQuestionResult').innerHTML=`<div class="dig-answer ${ok?'good':'bad'}">${escD(msg)}</div><div class="dig-modal-actions"><button class="dig-action-btn good" id="digQuestionDone">CONTINUAR · FIN DE TURNO</button></div>`;document.getElementById('digQuestionDone').onclick=finishTurn}
function cardText(c){return Object.values(c||{}).filter(v=>typeof v==='string').join(' ').toLowerCase()}function digitalCompatible(c){const t=cardText(c),bad=['ordena el mazo','ordenar el mazo','baraja el mazo','barajar el mazo','carta superior del mazo','carta de arriba del mazo','fondo del mazo','primeras cartas del mazo','primeras 3 cartas','primeras tres cartas'];return !bad.some(x=>t.includes(x))}function pickCompatible(pool,key){let compatible=pool.filter(digitalCompatible);if(!compatible.length)compatible=pool;return digPick(compatible,key)}
function digitalInstinctCard(){const choices=['efecto'];if(dig.players.length>=3)choices.push('quien');const kind=randomFrom(choices);if(kind==='efecto')return {kind,c:pickCompatible(DATA.instinto_efectos,'dig20_inst_ef')};return {kind,c:pickCompatible(DATA.instinto_quien,'dig20_inst_qmp')}}
function showDigitalAction(kind){let title='',body='',saveMeta=null;if(kind==='choose'){const c=pickCompatible(DATA.elige_tu,'dig20_choose');title='🔴 ELIGE TÚ';body=`<div class="dig-effect-card"><p class="ef">${escD(c?.texto||'No quedan cartas compatibles.')}</p></div>`;if(c)saveMeta={title:'ELIGE TÚ',effect:c.texto}}else if(kind==='things'){const c=pickCompatible(DATA.cosas_que_pasan,'dig20_things');title='🟡 COSAS QUE PASAN';body=c?`<div class="dig-effect-card"><h3>${escD(c.titulo)}</h3><p class="fl">${escD(c.frase)}</p><p class="ef">${escD(c.efecto)}</p></div>`:'<p>No quedan cartas compatibles.</p>';if(c)saveMeta={title:c.titulo,effect:c.efecto}}else{const r=digitalInstinctCard(),c=r.c;title=r.kind==='efecto'?'🔵 INSTINTO · PODER':'🔵 INSTINTO · ¿QUIÉN ES MÁS PROBABLE?';if(!c)body='<p>No quedan cartas compatibles.</p>';else if(r.kind==='efecto'){body=`<div class="dig-effect-card"><h3>${escD(c.titulo)}</h3><p class="fl">${escD(c.frase)}</p><p class="ef">${escD(c.efecto)}</p></div>`;saveMeta={title:c.titulo,effect:c.efecto}}else body=`<div class="dig-effect-card"><h3>${escD(c.pregunta)}</h3><p class="ef">👉 Señala a un jugador.</p><p style="font-size:.78rem;color:#b8bbc6">⚖️ Si el resto está de acuerdo, dale un Defecto o roba una Virtud. Si no, el señalado te entrega un Defecto o te exige una Virtud.</p></div>`}const render=()=>{openOverlay(`<p class="dig-modal-kicker">CASILLA DEL TABLERO</p><h2>${title}</h2>${body}<div class="dig-modal-actions">${saveMeta?'<button class="dig-action-btn" id="digSaveEffect">💾 GUARDAR EFECTO</button>':''}<button class="dig-action-btn" id="digAdjust">🎒 APLICAR CONSECUENCIA</button><button class="dig-action-btn good" id="digActionDone">✅ RESUELTO · FIN DE TURNO</button></div>`);if(saveMeta)document.getElementById('digSaveEffect').onclick=()=>{const p=currentPlayer();p.effects.push({...saveMeta,id:`e${Date.now()}`});saveDig();document.getElementById('digSaveEffect').textContent='✓ GUARDADO';document.getElementById('digSaveEffect').disabled=true};document.getElementById('digAdjust').onclick=()=>showResources(render);document.getElementById('digActionDone').onclick=finishTurn};render()}
function showResources(backFn){const p=currentPlayer(),targets=new Set(targetNums(p.character));const render=()=>{openOverlay(`<p class="dig-modal-kicker">SOLO ${escD(p.name).toUpperCase()}</p><h2>🎒 Recursos</h2><div class="dig-private">Las preguntas ya suman Virtudes y Defectos automáticamente. Usa + y − solo para robos, regalos o consecuencias especiales.</div>${[1,2,3,4,5,6,7,8,9].map(n=>`<div class="dig-resource-row"><div class="dig-resource ${targets.has(n)?'target':''}"><strong>✨ ${VIRTUES[n]} ${targets.has(n)?'⭐':''}</strong><small>${NAMES[n]}</small><div class="dig-counter"><button data-res="v" data-n="${n}" data-d="-1">−</button><span>${p.virtues[n]||0}</span><button data-res="v" data-n="${n}" data-d="1">+</button></div></div><div class="dig-vs">/</div><div class="dig-resource"><strong>☠️ ${DEFECTS[n]}</strong><small>${NAMES[n]}</small><div class="dig-counter"><button data-res="d" data-n="${n}" data-d="-1">−</button><span>${p.defects[n]||0}</span><button data-res="d" data-n="${n}" data-d="1">+</button></div></div></div>`).join('')}<div class="dig-modal-actions"><button class="dig-action-btn good" id="digResourcesDone">${backFn?'← VOLVER A LA CARTA':'🙈 OCULTAR'}</button></div>`);document.querySelectorAll('[data-res]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.n),delta=Number(b.dataset.d),obj=b.dataset.res==='v'?p.virtues:p.defects;obj[n]=Math.max(0,(obj[n]||0)+delta);saveDig();render()});document.getElementById('digResourcesDone').onclick=()=>{if(checkWin(p)){dig.winner=p.id;saveDig();closeOverlay();renderDigitalGame();return}if(backFn)backFn();else closeOverlay()}};render()}
function showEffects(){const p=currentPlayer();const render=()=>{openOverlay(`<p class="dig-modal-kicker">SOLO ${escD(p.name).toUpperCase()}</p><h2>⚡ Efectos guardados</h2>${p.effects.length?p.effects.map(e=>`<div class="dig-effect-card"><h3>${escD(e.title)}</h3><p class="ef">${escD(e.effect)}</p><button class="dig-action-btn ghost" data-del-eff="${e.id}">USAR / DESCARTAR</button></div>`).join(''):'<p style="color:#9da0ad">No tienes efectos pendientes.</p>'}<div class="dig-modal-actions"><button class="dig-action-btn good" id="digEffectsClose">🙈 OCULTAR</button></div>`);document.querySelectorAll('[data-del-eff]').forEach(b=>b.onclick=()=>{p.effects=p.effects.filter(e=>e.id!==b.dataset.delEff);saveDig();render()});document.getElementById('digEffectsClose').onclick=closeOverlay};render()}
function hookExisting(){const start=document.getElementById('startGame');if(start)start.onclick=showModes;document.getElementById('modePhysical').onclick=()=>{activate(document.getElementById('home'));showHome();const r=document.getElementById('resetTop');if(r)r.style.display=''};document.getElementById('modeDigital').onclick=showSetup;document.getElementById('modeBack').onclick=()=>{allScreens().forEach(s=>s.classList.remove('active'));document.getElementById('introScreen').classList.add('active');document.body.classList.add('intro-mode');scrollTo(0,0)};document.getElementById('digPlayerCount').onchange=renderNameInputs;document.getElementById('digCreate').onclick=createDigitalGame;document.getElementById('digSetupBack').onclick=showModes;renderNameInputs()}
injectCSS();buildScreens();hookExisting();
})();